// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: recordsorg.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ordering int32

const (
	Ordering_UNKNOWN  Ordering = 0
	Ordering_BY_LABEL Ordering = 1
)

// Enum value maps for Ordering.
var (
	Ordering_name = map[int32]string{
		0: "UNKNOWN",
		1: "BY_LABEL",
	}
	Ordering_value = map[string]int32{
		"UNKNOWN":  0,
		"BY_LABEL": 1,
	}
)

func (x Ordering) Enum() *Ordering {
	p := new(Ordering)
	*p = x
	return p
}

func (x Ordering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ordering) Descriptor() protoreflect.EnumDescriptor {
	return file_recordsorg_proto_enumTypes[0].Descriptor()
}

func (Ordering) Type() protoreflect.EnumType {
	return &file_recordsorg_proto_enumTypes[0]
}

func (x Ordering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ordering.Descriptor instead.
func (Ordering) EnumDescriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{0}
}

type Org struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties []*FolderProperties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *Org) Reset() {
	*x = Org{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{0}
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Org) GetProperties() []*FolderProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type FolderProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FolderNumber int32    `protobuf:"varint,1,opt,name=folder_number,json=folderNumber,proto3" json:"folder_number,omitempty"`
	Index        int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Ordering     Ordering `protobuf:"varint,3,opt,name=ordering,proto3,enum=recordsorg.Ordering" json:"ordering,omitempty"`
	PreSpace     bool     `protobuf:"varint,4,opt,name=pre_space,json=preSpace,proto3" json:"pre_space,omitempty"`
}

func (x *FolderProperties) Reset() {
	*x = FolderProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FolderProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderProperties) ProtoMessage() {}

func (x *FolderProperties) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderProperties.ProtoReflect.Descriptor instead.
func (*FolderProperties) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{1}
}

func (x *FolderProperties) GetFolderNumber() int32 {
	if x != nil {
		return x.FolderNumber
	}
	return 0
}

func (x *FolderProperties) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FolderProperties) GetOrdering() Ordering {
	if x != nil {
		return x.Ordering
	}
	return Ordering_UNKNOWN
}

func (x *FolderProperties) GetPreSpace() bool {
	if x != nil {
		return x.PreSpace
	}
	return false
}

type OrderCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cache map[int32]*CacheStore `protobuf:"bytes,1,rep,name=cache,proto3" json:"cache,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OrderCache) Reset() {
	*x = OrderCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCache) ProtoMessage() {}

func (x *OrderCache) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCache.ProtoReflect.Descriptor instead.
func (*OrderCache) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCache) GetCache() map[int32]*CacheStore {
	if x != nil {
		return x.Cache
	}
	return nil
}

type CacheStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orderings []*CacheHolding `protobuf:"bytes,1,rep,name=orderings,proto3" json:"orderings,omitempty"`
	Width     float32         `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *CacheStore) Reset() {
	*x = CacheStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStore) ProtoMessage() {}

func (x *CacheStore) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStore.ProtoReflect.Descriptor instead.
func (*CacheStore) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{3}
}

func (x *CacheStore) GetOrderings() []*CacheHolding {
	if x != nil {
		return x.Orderings
	}
	return nil
}

func (x *CacheStore) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type CacheHolding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordering    Ordering `protobuf:"varint,1,opt,name=ordering,proto3,enum=recordsorg.Ordering" json:"ordering,omitempty"`
	OrderString string   `protobuf:"bytes,2,opt,name=order_string,json=orderString,proto3" json:"order_string,omitempty"`
}

func (x *CacheHolding) Reset() {
	*x = CacheHolding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheHolding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHolding) ProtoMessage() {}

func (x *CacheHolding) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHolding.ProtoReflect.Descriptor instead.
func (*CacheHolding) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{4}
}

func (x *CacheHolding) GetOrdering() Ordering {
	if x != nil {
		return x.Ordering
	}
	return Ordering_UNKNOWN
}

func (x *CacheHolding) GetOrderString() string {
	if x != nil {
		return x.OrderString
	}
	return ""
}

var File_recordsorg_proto protoreflect.FileDescriptor

var file_recordsorg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x22, 0x57,
	0x0a, 0x03, 0x4f, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x10, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x30, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65,
	0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72,
	0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x50,
	0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x5a, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x36,
	0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22, 0x63, 0x0a, 0x0c,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x2a, 0x25, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x59,
	0x5f, 0x4c, 0x41, 0x42, 0x45, 0x4c, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recordsorg_proto_rawDescOnce sync.Once
	file_recordsorg_proto_rawDescData = file_recordsorg_proto_rawDesc
)

func file_recordsorg_proto_rawDescGZIP() []byte {
	file_recordsorg_proto_rawDescOnce.Do(func() {
		file_recordsorg_proto_rawDescData = protoimpl.X.CompressGZIP(file_recordsorg_proto_rawDescData)
	})
	return file_recordsorg_proto_rawDescData
}

var file_recordsorg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recordsorg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_recordsorg_proto_goTypes = []interface{}{
	(Ordering)(0),            // 0: recordsorg.Ordering
	(*Org)(nil),              // 1: recordsorg.Org
	(*FolderProperties)(nil), // 2: recordsorg.FolderProperties
	(*OrderCache)(nil),       // 3: recordsorg.OrderCache
	(*CacheStore)(nil),       // 4: recordsorg.CacheStore
	(*CacheHolding)(nil),     // 5: recordsorg.CacheHolding
	nil,                      // 6: recordsorg.OrderCache.CacheEntry
}
var file_recordsorg_proto_depIdxs = []int32{
	2, // 0: recordsorg.Org.properties:type_name -> recordsorg.FolderProperties
	0, // 1: recordsorg.FolderProperties.ordering:type_name -> recordsorg.Ordering
	6, // 2: recordsorg.OrderCache.cache:type_name -> recordsorg.OrderCache.CacheEntry
	5, // 3: recordsorg.CacheStore.orderings:type_name -> recordsorg.CacheHolding
	0, // 4: recordsorg.CacheHolding.ordering:type_name -> recordsorg.Ordering
	4, // 5: recordsorg.OrderCache.CacheEntry.value:type_name -> recordsorg.CacheStore
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_recordsorg_proto_init() }
func file_recordsorg_proto_init() {
	if File_recordsorg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recordsorg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Org); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FolderProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheHolding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recordsorg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recordsorg_proto_goTypes,
		DependencyIndexes: file_recordsorg_proto_depIdxs,
		EnumInfos:         file_recordsorg_proto_enumTypes,
		MessageInfos:      file_recordsorg_proto_msgTypes,
	}.Build()
	File_recordsorg_proto = out.File
	file_recordsorg_proto_rawDesc = nil
	file_recordsorg_proto_goTypes = nil
	file_recordsorg_proto_depIdxs = nil
}
