// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: recordsorg.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ordering int32

const (
	Ordering_ORDERING_UNSPECIFIED   Ordering = 0
	Ordering_ORDERING_BY_LABEL      Ordering = 1
	Ordering_ORDERING_BY_DATE_ADDED Ordering = 2
)

// Enum value maps for Ordering.
var (
	Ordering_name = map[int32]string{
		0: "ORDERING_UNSPECIFIED",
		1: "ORDERING_BY_LABEL",
		2: "ORDERING_BY_DATE_ADDED",
	}
	Ordering_value = map[string]int32{
		"ORDERING_UNSPECIFIED":   0,
		"ORDERING_BY_LABEL":      1,
		"ORDERING_BY_DATE_ADDED": 2,
	}
)

func (x Ordering) Enum() *Ordering {
	p := new(Ordering)
	*p = x
	return p
}

func (x Ordering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ordering) Descriptor() protoreflect.EnumDescriptor {
	return file_recordsorg_proto_enumTypes[0].Descriptor()
}

func (Ordering) Type() protoreflect.EnumType {
	return &file_recordsorg_proto_enumTypes[0]
}

func (x Ordering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ordering.Descriptor instead.
func (Ordering) EnumDescriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{0}
}

type OrgConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orgs []*Org `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
}

func (x *OrgConfig) Reset() {
	*x = OrgConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgConfig) ProtoMessage() {}

func (x *OrgConfig) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgConfig.ProtoReflect.Descriptor instead.
func (*OrgConfig) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{0}
}

func (x *OrgConfig) GetOrgs() []*Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type Org struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties []*FolderProperties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	Slots      []*Slot             `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	Orderings  []*BuiltOrdering    `protobuf:"bytes,4,rep,name=orderings,proto3" json:"orderings,omitempty"`
}

func (x *Org) Reset() {
	*x = Org{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{1}
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Org) GetProperties() []*FolderProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Org) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *Org) GetOrderings() []*BuiltOrdering {
	if x != nil {
		return x.Orderings
	}
	return nil
}

type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotNumber int32   `protobuf:"varint,1,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	SlotWidth  float32 `protobuf:"fixed32,2,opt,name=slot_width,json=slotWidth,proto3" json:"slot_width,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{2}
}

func (x *Slot) GetSlotNumber() int32 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

func (x *Slot) GetSlotWidth() float32 {
	if x != nil {
		return x.SlotWidth
	}
	return 0
}

type BuiltOrdering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotNumber int32 `protobuf:"varint,1,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	Index      int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	InstanceId int32 `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FromFolder int32 `protobuf:"varint,4,opt,name=from_folder,json=fromFolder,proto3" json:"from_folder,omitempty"`
}

func (x *BuiltOrdering) Reset() {
	*x = BuiltOrdering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuiltOrdering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltOrdering) ProtoMessage() {}

func (x *BuiltOrdering) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltOrdering.ProtoReflect.Descriptor instead.
func (*BuiltOrdering) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{3}
}

func (x *BuiltOrdering) GetSlotNumber() int32 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

func (x *BuiltOrdering) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BuiltOrdering) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *BuiltOrdering) GetFromFolder() int32 {
	if x != nil {
		return x.FromFolder
	}
	return 0
}

type FolderProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FolderNumber int32    `protobuf:"varint,1,opt,name=folder_number,json=folderNumber,proto3" json:"folder_number,omitempty"`
	Index        int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Order        Ordering `protobuf:"varint,3,opt,name=order,proto3,enum=recordsorg.Ordering" json:"order,omitempty"`
	PreSpace     bool     `protobuf:"varint,4,opt,name=pre_space,json=preSpace,proto3" json:"pre_space,omitempty"`
}

func (x *FolderProperties) Reset() {
	*x = FolderProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FolderProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderProperties) ProtoMessage() {}

func (x *FolderProperties) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderProperties.ProtoReflect.Descriptor instead.
func (*FolderProperties) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{4}
}

func (x *FolderProperties) GetFolderNumber() int32 {
	if x != nil {
		return x.FolderNumber
	}
	return 0
}

func (x *FolderProperties) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FolderProperties) GetOrder() Ordering {
	if x != nil {
		return x.Order
	}
	return Ordering_ORDERING_UNSPECIFIED
}

func (x *FolderProperties) GetPreSpace() bool {
	if x != nil {
		return x.PreSpace
	}
	return false
}

type OrderCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cache map[int32]*CacheStore `protobuf:"bytes,1,rep,name=cache,proto3" json:"cache,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OrderCache) Reset() {
	*x = OrderCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCache) ProtoMessage() {}

func (x *OrderCache) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCache.ProtoReflect.Descriptor instead.
func (*OrderCache) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCache) GetCache() map[int32]*CacheStore {
	if x != nil {
		return x.Cache
	}
	return nil
}

type CacheStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orderings []*CacheHolding `protobuf:"bytes,1,rep,name=orderings,proto3" json:"orderings,omitempty"`
	Width     float32         `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *CacheStore) Reset() {
	*x = CacheStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStore) ProtoMessage() {}

func (x *CacheStore) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStore.ProtoReflect.Descriptor instead.
func (*CacheStore) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{6}
}

func (x *CacheStore) GetOrderings() []*CacheHolding {
	if x != nil {
		return x.Orderings
	}
	return nil
}

func (x *CacheStore) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type CacheHolding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordering    Ordering `protobuf:"varint,1,opt,name=ordering,proto3,enum=recordsorg.Ordering" json:"ordering,omitempty"`
	OrderString string   `protobuf:"bytes,2,opt,name=order_string,json=orderString,proto3" json:"order_string,omitempty"`
}

func (x *CacheHolding) Reset() {
	*x = CacheHolding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheHolding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHolding) ProtoMessage() {}

func (x *CacheHolding) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHolding.ProtoReflect.Descriptor instead.
func (*CacheHolding) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{7}
}

func (x *CacheHolding) GetOrdering() Ordering {
	if x != nil {
		return x.Ordering
	}
	return Ordering_ORDERING_UNSPECIFIED
}

func (x *CacheHolding) GetOrderString() string {
	if x != nil {
		return x.OrderString
	}
	return ""
}

type GetOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgName string `protobuf:"bytes,1,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
}

func (x *GetOrgRequest) Reset() {
	*x = GetOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgRequest) ProtoMessage() {}

func (x *GetOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgRequest.ProtoReflect.Descriptor instead.
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrgRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type GetOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Org *Org `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
}

func (x *GetOrgResponse) Reset() {
	*x = GetOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordsorg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgResponse) ProtoMessage() {}

func (x *GetOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordsorg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgResponse.ProtoReflect.Descriptor instead.
func (*GetOrgResponse) Descriptor() ([]byte, []int) {
	return file_recordsorg_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

var File_recordsorg_proto protoreflect.FileDescriptor

var file_recordsorg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x22, 0x30,
	0x0a, 0x09, 0x4f, 0x72, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x04, 0x6f,
	0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x04, 0x6f, 0x72, 0x67, 0x73,
	0x22, 0xb8, 0x01, 0x0a, 0x03, 0x4f, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x46, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f,
	0x74, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f,
	0x72, 0x67, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x46, 0x0a, 0x04, 0x53,
	0x6c, 0x6f, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x96,
	0x01, 0x0a, 0x10, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72,
	0x65, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f,
	0x72, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a,
	0x50, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x5a, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x36, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22, 0x63, 0x0a,
	0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x22, 0x2a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x03,
	0x6f, 0x72, 0x67, 0x2a, 0x57, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x0a, 0x14, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x42, 0x59, 0x5f, 0x4c, 0x41, 0x42, 0x45, 0x4c, 0x10, 0x01,
	0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x42, 0x59, 0x5f,
	0x44, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x02, 0x32, 0x56, 0x0a, 0x11,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x41, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x12, 0x19, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x6f, 0x72, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recordsorg_proto_rawDescOnce sync.Once
	file_recordsorg_proto_rawDescData = file_recordsorg_proto_rawDesc
)

func file_recordsorg_proto_rawDescGZIP() []byte {
	file_recordsorg_proto_rawDescOnce.Do(func() {
		file_recordsorg_proto_rawDescData = protoimpl.X.CompressGZIP(file_recordsorg_proto_rawDescData)
	})
	return file_recordsorg_proto_rawDescData
}

var file_recordsorg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recordsorg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recordsorg_proto_goTypes = []interface{}{
	(Ordering)(0),            // 0: recordsorg.Ordering
	(*OrgConfig)(nil),        // 1: recordsorg.OrgConfig
	(*Org)(nil),              // 2: recordsorg.Org
	(*Slot)(nil),             // 3: recordsorg.Slot
	(*BuiltOrdering)(nil),    // 4: recordsorg.BuiltOrdering
	(*FolderProperties)(nil), // 5: recordsorg.FolderProperties
	(*OrderCache)(nil),       // 6: recordsorg.OrderCache
	(*CacheStore)(nil),       // 7: recordsorg.CacheStore
	(*CacheHolding)(nil),     // 8: recordsorg.CacheHolding
	(*GetOrgRequest)(nil),    // 9: recordsorg.GetOrgRequest
	(*GetOrgResponse)(nil),   // 10: recordsorg.GetOrgResponse
	nil,                      // 11: recordsorg.OrderCache.CacheEntry
}
var file_recordsorg_proto_depIdxs = []int32{
	2,  // 0: recordsorg.OrgConfig.orgs:type_name -> recordsorg.Org
	5,  // 1: recordsorg.Org.properties:type_name -> recordsorg.FolderProperties
	3,  // 2: recordsorg.Org.slots:type_name -> recordsorg.Slot
	4,  // 3: recordsorg.Org.orderings:type_name -> recordsorg.BuiltOrdering
	0,  // 4: recordsorg.FolderProperties.order:type_name -> recordsorg.Ordering
	11, // 5: recordsorg.OrderCache.cache:type_name -> recordsorg.OrderCache.CacheEntry
	8,  // 6: recordsorg.CacheStore.orderings:type_name -> recordsorg.CacheHolding
	0,  // 7: recordsorg.CacheHolding.ordering:type_name -> recordsorg.Ordering
	2,  // 8: recordsorg.GetOrgResponse.org:type_name -> recordsorg.Org
	7,  // 9: recordsorg.OrderCache.CacheEntry.value:type_name -> recordsorg.CacheStore
	9,  // 10: recordsorg.RecordsOrgService.GetOrg:input_type -> recordsorg.GetOrgRequest
	10, // 11: recordsorg.RecordsOrgService.GetOrg:output_type -> recordsorg.GetOrgResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_recordsorg_proto_init() }
func file_recordsorg_proto_init() {
	if File_recordsorg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recordsorg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Org); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuiltOrdering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FolderProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheHolding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recordsorg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recordsorg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recordsorg_proto_goTypes,
		DependencyIndexes: file_recordsorg_proto_depIdxs,
		EnumInfos:         file_recordsorg_proto_enumTypes,
		MessageInfos:      file_recordsorg_proto_msgTypes,
	}.Build()
	File_recordsorg_proto = out.File
	file_recordsorg_proto_rawDesc = nil
	file_recordsorg_proto_goTypes = nil
	file_recordsorg_proto_depIdxs = nil
}
